apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-staticroute-operator
spec:
  selector:
    matchLabels:
      name: k8s-staticroute-operator
  template:
    metadata:
      labels:
        name: k8s-staticroute-operator
    spec:
      serviceAccountName: k8s-staticroute-operator
      hostNetwork: true
      tolerations:
        - operator: Exists
      containers:
        - name: k8s-staticroute-operator
          image: digitalocean/k8s-staticroute-operator:<OPERATOR_RELEASE>
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: OPERATOR_NAME
              value: "k8s-staticroute-operator"
            - name: NODE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
