apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-staticroute-operator
spec:
  selector:
    matchLabels:
      name: k8s-staticroute-operator
  template:
    metadata:
      labels:
        name: k8s-staticroute-operator
    spec:
      serviceAccountName: k8s-staticroute-operator
      hostNetwork: true
      tolerations:
        - operator: Exists
      imagePullSecrets:
        - name: <PULL_SECRET_NAME>
      initContainers:
        - name: init-network
          image: alpine:3.20
          command: ["sysctl", "-w", "net.ipv4.fib_multipath_hash_policy=1"]
          securityContext:
            readOnlyRootFilesystem: true
            privileged: true
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: k8s-staticroute-operator
          image: <CONTAINER_REGISTRY>/k8s-staticroute-operator:<OPERATOR_RELEASE>
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "150Mi"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: OPERATOR_NAME
              value: "k8s-staticroute-operator"
            - name: NODE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
