apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-staticroute-operator-worker
spec:
  selector:
    matchLabels:
      name: k8s-staticroute-operator-worker
  template:
    metadata:
      labels:
        name: k8s-staticroute-operator-worker
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
      imagePullSecrets:
        - name: <PULL_SECRET_NAME>
      initContainers:
        - name: init-network
          image: <CONTAINER_REGISTRY>/k8s-staticroute-operator:<OPERATOR_RELEASE>
          imagePullPolicy: Always
          args: ["init"]
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: k8s-staticroute-operator-worker
          image: <CONTAINER_REGISTRY>/k8s-staticroute-operator:<OPERATOR_RELEASE>
          imagePullPolicy: Always
          args: ["worker"]
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "150Mi"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: static-route-operator-token
                  key: service-token