---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-staticroute-operator
subjects:
  - kind: ServiceAccount
    name: k8s-staticroute-operator
roleRef:
  kind: ClusterRole
  name: k8s-staticroute-operator
  apiGroup: rbac.authorization.k8s.io
