apiVersion: v1
kind: Namespace
metadata:
  annotations:
    provider: digitalocean
  name: static-routes
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    provider: digitalocean
  name: staticroutes.networking.digitalocean.com
spec:
  group: networking.digitalocean.com
  names:
    kind: StaticRoute
    plural: staticroutes
    shortNames:
    - sr
    singular: staticroute
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      priority: 0
      type: date
    - description: Destination host(s)/subnet(s)
      jsonPath: .spec.destinations
      name: Destinations
      priority: 1
      type: string
    - description: Gateway to route through
      jsonPath: .spec.gateway
      name: Gateway
      priority: 1
      type: string
    - description: Gateways list for multipath routing
      jsonPath: .spec.multipath
      name: Multipath
      priority: 1
      type: string
    - description: Sets the policy for apply this route set
      jsonPath: .spec.nodeSelector
      name: NodeSelector
      priority: 1
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              destinations:
                description: Destination host(s)/subnet(s) to route through the gateway
                  (required)
                items:
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$|^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
                  type: string
                type: array
              gateway:
                description: Gateway to route through
                pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
                type: string
              multipath:
                items:
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
                  type: string
                type: array
              nodeSelector:
                description: Sets the policy for apply this route set
                properties:
                  key:
                    type: string
                  operation:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - key
                - operation
                - values
                type: object
            required:
            - destinations
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator
  namespace: static-routes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator
rules:
- apiGroups:
  - networking.digitalocean.com
  resources:
  - clusterkopfpeerings
  verbs:
  - list
  - watch
  - patch
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - networking.digitalocean.com
  resources:
  - staticroutes
  verbs:
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-staticroute-operator
subjects:
- kind: ServiceAccount
  name: k8s-staticroute-operator
  namespace: static-routes
---
apiVersion: v1
data:
  service-token: <USE YOUR OWN VALUE>
kind: Secret
metadata:
  annotations:
    provider: digitalocean
  name: static-route-operator-token
  namespace: static-routes
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator-service
  namespace: static-routes
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    name: k8s-staticroute-operator-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator
  namespace: static-routes
spec:
  replicas: 2
  selector:
    matchLabels:
      name: k8s-staticroute-operator
  template:
    metadata:
      annotations:
        provider: digitalocean
      labels:
        name: k8s-staticroute-operator
    spec:
      containers:
      - env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: service-token
              name: static-route-operator-token
        - name: OPERATOR_NAME
          value: k8s-staticroute-operator
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: registry.digitalocean.com/cto-ai/k8s-staticroute-operator:v1.0.4
        imagePullPolicy: Always
        name: k8s-staticroute-operator
        resources:
          limits:
            memory: 150Mi
          requests:
            memory: 100Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: registry-cto-ai
      serviceAccountName: k8s-staticroute-operator
      tolerations:
      - operator: Exists
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator-service
  namespace: static-routes
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-staticroute-operator-service
  template:
    metadata:
      annotations:
        provider: digitalocean
      labels:
        name: k8s-staticroute-operator-service
    spec:
      containers:
      - args:
        - service
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: service-token
              name: static-route-operator-token
        image: registry.digitalocean.com/cto-ai/k8s-staticroute-operator:v1.0.4
        imagePullPolicy: Always
        name: k8s-staticroute-operator-service
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /db
          name: routes-db-pvc
      imagePullSecrets:
      - name: registry-cto-ai
      tolerations:
      - operator: Exists
  volumeClaimTemplates:
  - metadata:
      name: routes-db-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator-worker
  namespace: static-routes
spec:
  selector:
    matchLabels:
      name: k8s-staticroute-operator-worker
  template:
    metadata:
      annotations:
        provider: digitalocean
      labels:
        name: k8s-staticroute-operator-worker
    spec:
      containers:
      - args:
        - worker
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: service-token
              name: static-route-operator-token
        image: registry.digitalocean.com/cto-ai/k8s-staticroute-operator:v1.0.4
        imagePullPolicy: Always
        name: k8s-staticroute-operator-worker
        resources:
          limits:
            memory: 150Mi
          requests:
            memory: 100Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      imagePullSecrets:
      - name: registry-cto-ai
      initContainers:
      - args:
        - init
        image: registry.digitalocean.com/cto-ai/k8s-staticroute-operator:v1.0.4
        imagePullPolicy: Always
        name: init-network
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
          runAsUser: 0
      tolerations:
      - operator: Exists
