apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Making sure all resources are created in a dedicated namespace
# Also specific labels and annotations are added for later identification
namespace: static-routes
commonAnnotations:
  provider: digitalocean

# Apply all required resources: RBACs, CRD definitions, operator running context (DaemonSet)
resources:
  - config/namespace.yaml
  - config/rbac/service_account.yaml
  - config/rbac/role.yaml
  - config/rbac/role_binding.yaml
  - config/crd.yaml
  - config/manager.yaml
