apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticroutes.kopf.dev
spec:
  scope: Cluster
  group: kopf.dev
  names:
    kind: StaticRoute
    plural: staticroutes
    singular: staticroute
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: Defines the desired state of a StaticRoute
              properties:
                destination:
                  type: string
                  description: Destination host/subnet to route through the gateway (required)
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$|^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
                gateway:
                  type: string
                  description: Gateway to route through (required)
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
              required:
                - destination
                - gateway
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Destination
          type: string
          description: Destination host/subnet
          jsonPath: .spec.destination
        - name: Gateway
          type: string
          description: Gateway to route through
          jsonPath: .spec.gateway
        # - name: Status
        #   type: string
        #   description: Static route status
        #   jsonPath: .status.create_fn.routeCreateStatus
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
